"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9913860df6af

from __future__ import annotations
from enum import Enum
from mollie import utils


class AccountStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the business account."""

    ACTIVE = "active"
    BLOCKED = "blocked"
    CLOSED = "closed"
