"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 330a16854c16

from __future__ import annotations
from .mode import Mode
from .url import URL, URLTypedDict
from enum import Enum
from mollie import models, utils
from mollie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EntityPairingCodeStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the pairing code."""

    ACTIVE = "active"
    EXPIRED = "expired"
    REVOKED = "revoked"


class EntityPairingCodeQrCodeTypedDict(TypedDict):
    r"""The QR code representation of the pairing code."""

    height: NotRequired[float]
    width: NotRequired[float]
    src: NotRequired[str]


class EntityPairingCodeQrCode(BaseModel):
    r"""The QR code representation of the pairing code."""

    height: Optional[float] = None

    width: Optional[float] = None

    src: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["height", "width", "src"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EntityPairingCodeDetailsTypedDict(TypedDict):
    r"""Additional pairing code data, present only when requested via the `include` parameter."""

    qr_code: NotRequired[Nullable[EntityPairingCodeQrCodeTypedDict]]
    r"""The QR code representation of the pairing code."""


class EntityPairingCodeDetails(BaseModel):
    r"""Additional pairing code data, present only when requested via the `include` parameter."""

    qr_code: Annotated[
        OptionalNullable[EntityPairingCodeQrCode], pydantic.Field(alias="qrCode")
    ] = UNSET
    r"""The QR code representation of the pairing code."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["qrCode"])
        nullable_fields = set(["qrCode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class EntityPairingCodeLinksTypedDict(TypedDict):
    r"""An object with several relevant URLs. Every URL object will contain an `href` and a `type` field."""

    self_: URLTypedDict
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""
    profile: URLTypedDict
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""
    documentation: URLTypedDict
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""


class EntityPairingCodeLinks(BaseModel):
    r"""An object with several relevant URLs. Every URL object will contain an `href` and a `type` field."""

    self_: Annotated[URL, pydantic.Field(alias="self")]
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""

    profile: URL
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""

    documentation: URL
    r"""In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field."""


class EntityPairingCodeTypedDict(TypedDict):
    resource: str
    r"""Indicates the response contains a terminal pairing code object. Will always contain the string
    `terminal-pairing-code` for this endpoint.
    """
    id: str
    r"""The unique identifier of the pairing code. Example: `termpc_R7gX5Ea9bC4DkFj3G`."""
    mode: Mode
    r"""Whether this entity was created in live mode or in test mode."""
    code: str
    r"""The human-readable pairing code to be entered on the terminal. This code is multi-use and will expire after the
    time indicated in `expiresAt`.
    """
    profile_id: str
    r"""The ID of the profile the terminal is being paired with."""
    status: EntityPairingCodeStatus
    expires_at: str
    r"""The date and time the pairing code expires, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. Pairing
    codes expire 90 days after creation. After this time, the code can no longer be used to pair a terminal.
    """
    created_at: str
    r"""The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format."""
    links: EntityPairingCodeLinksTypedDict
    r"""An object with several relevant URLs. Every URL object will contain an `href` and a `type` field."""
    details: NotRequired[Nullable[EntityPairingCodeDetailsTypedDict]]
    r"""Additional pairing code data, present only when requested via the `include` parameter."""
    revoked_at: NotRequired[Nullable[str]]
    r"""The date and time the pairing code was revoked, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    `null` if the code has not been revoked.
    """


class EntityPairingCode(BaseModel):
    resource: str
    r"""Indicates the response contains a terminal pairing code object. Will always contain the string
    `terminal-pairing-code` for this endpoint.
    """

    id: str
    r"""The unique identifier of the pairing code. Example: `termpc_R7gX5Ea9bC4DkFj3G`."""

    mode: Mode
    r"""Whether this entity was created in live mode or in test mode."""

    code: str
    r"""The human-readable pairing code to be entered on the terminal. This code is multi-use and will expire after the
    time indicated in `expiresAt`.
    """

    profile_id: Annotated[str, pydantic.Field(alias="profileId")]
    r"""The ID of the profile the terminal is being paired with."""

    status: EntityPairingCodeStatus

    expires_at: Annotated[str, pydantic.Field(alias="expiresAt")]
    r"""The date and time the pairing code expires, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. Pairing
    codes expire 90 days after creation. After this time, the code can no longer be used to pair a terminal.
    """

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]
    r"""The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format."""

    links: Annotated[EntityPairingCodeLinks, pydantic.Field(alias="_links")]
    r"""An object with several relevant URLs. Every URL object will contain an `href` and a `type` field."""

    details: OptionalNullable[EntityPairingCodeDetails] = UNSET
    r"""Additional pairing code data, present only when requested via the `include` parameter."""

    revoked_at: Annotated[OptionalNullable[str], pydantic.Field(alias="revokedAt")] = (
        UNSET
    )
    r"""The date and time the pairing code was revoked, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    `null` if the code has not been revoked.
    """

    @field_serializer("mode")
    def serialize_mode(self, value):
        if isinstance(value, str):
            try:
                return models.Mode(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.EntityPairingCodeStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["details", "revokedAt"])
        nullable_fields = set(["details", "revokedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    EntityPairingCodeDetails.model_rebuild()
except NameError:
    pass
try:
    EntityPairingCodeLinks.model_rebuild()
except NameError:
    pass
try:
    EntityPairingCode.model_rebuild()
except NameError:
    pass
