"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 57d854f48dfc

from __future__ import annotations
from enum import Enum
from mollie import utils


class SessionRequiredCustomerDetailsResponse(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Customer details that should be collected during checkout."""

    EMAIL = "email"
    BILLING_ADDRESS = "billing-address"
    SHIPPING_ADDRESS = "shipping-address"
