"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: dde27618d36e

from .basesdk import BaseSDK
from jsonpath import JSONPath
from mollie import models, utils
from mollie._hooks import HookContext
from mollie.types import OptionalNullable, UNSET
from mollie.utils import get_security_from_env
from mollie.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Awaitable, Dict, List, Mapping, Optional, Union


class SalesInvoices(BaseSDK):
    def create(
        self,
        *,
        idempotency_key: Optional[str] = None,
        sales_invoice_request: Optional[
            Union[models.SalesInvoiceRequest, models.SalesInvoiceRequestTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Create sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        With the Sales Invoice API you can generate sales invoices to send to your customers.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param sales_invoice_request:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreateSalesInvoiceRequest(
            idempotency_key=idempotency_key,
            sales_invoice_request=utils.get_pydantic_model(
                sales_invoice_request, Optional[models.SalesInvoiceRequest]
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v2/sales-invoices",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.sales_invoice_request if request is not None else None,
                False,
                True,
                "json",
                Optional[models.SalesInvoiceRequest],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X POST https://api.mollie.com/v2/sales-invoices \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM" \\\n    -d "profileId=pfl_QkEhN94Ba" \\\n    -d "currency=EUR" \\\n    -d "paymentTerm=30 days" \\\n    -d "status=draft" \\\n    -d "recipientIdentifier=customer-12354123" \\\n    -d "recipient[type]=consumer" \\\n    -d "recipient[givenName]=Given" \\\n    -d "recipient[familyName]=Family" \\\n    -d "recipient[email]=given.family@mollie.com" \\\n    -d "recipient[postalCode]=1000 AA" \\\n    -d "recipient[streetAndNumber]=Street 1" \\\n    -d "recipient[city]=Amsterdam" \\\n    -d "recipient[country]=nl" \\\n    -d "recipient[locale]=nl_NL" \\\n    -d "lines[0][description]=Product number 1" \\\n    -d "lines[0][quantity]=1" \\\n    -d "lines[0][vatRate]=21.00" \\\n    -d "lines[0][unitPrice][currency]=EUR" \\\n    -d "lines[0][unitPrice][value]=12.50" \\\n    -d "isEInvoice=false"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\CreateSalesInvoiceRequest;\nuse Mollie\\Api\\Http\\Data\\Money;\nuse Mollie\\Api\\Http\\Data\\Recipient;\nuse Mollie\\Api\\Http\\Data\\InvoiceLine;\nuse Mollie\\Api\\Http\\Data\\DataCollection;\nuse Mollie\\Api\\Types\\RecipientType;\nuse Mollie\\Api\\Types\\VatScheme;\nuse Mollie\\Api\\Types\\VatMode;\nuse Mollie\\Api\\Types\\PaymentTerm;\nuse Mollie\\Api\\Types\\SalesInvoiceStatus;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$recipient = new Recipient(\n    type: RecipientType::CONSUMER,\n    email: 'given.family@mollie.com',\n    streetAndNumber: 'Street 1',\n    postalCode: '1000 AA',\n    city: 'Amsterdam',\n    country: 'NL',\n    locale: 'nl_NL',\n    givenName: 'Given',\n    familyName: 'Family'\n);\n\n$invoiceLines = new DataCollection([\n    new InvoiceLine(\n        description: 'Product number 1',\n        quantity: 1,\n        vatRate: '21.00',\n        unitPrice: new Money(currency: 'EUR', value: '12.50')\n    )\n]);\n\n$request = new CreateSalesInvoiceRequest(\n    currency: 'EUR',\n    status: SalesInvoiceStatus::DRAFT,\n    vatScheme: VatScheme::STANDARD,\n    vatMode: VatMode::INCLUSIVE,\n    paymentTerm: PaymentTerm::DAYS_30,\n    recipientIdentifier: 'customer-12354123',\n    recipient: $recipient,\n    lines: $invoiceLines,\n    profileId: 'pfl_QkEhN94Ba',\n    isEInvoice: false\n);\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "201", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def create_async(
        self,
        *,
        idempotency_key: Optional[str] = None,
        sales_invoice_request: Optional[
            Union[models.SalesInvoiceRequest, models.SalesInvoiceRequestTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Create sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        With the Sales Invoice API you can generate sales invoices to send to your customers.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param sales_invoice_request:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreateSalesInvoiceRequest(
            idempotency_key=idempotency_key,
            sales_invoice_request=utils.get_pydantic_model(
                sales_invoice_request, Optional[models.SalesInvoiceRequest]
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v2/sales-invoices",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.sales_invoice_request if request is not None else None,
                False,
                True,
                "json",
                Optional[models.SalesInvoiceRequest],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X POST https://api.mollie.com/v2/sales-invoices \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM" \\\n    -d "profileId=pfl_QkEhN94Ba" \\\n    -d "currency=EUR" \\\n    -d "paymentTerm=30 days" \\\n    -d "status=draft" \\\n    -d "recipientIdentifier=customer-12354123" \\\n    -d "recipient[type]=consumer" \\\n    -d "recipient[givenName]=Given" \\\n    -d "recipient[familyName]=Family" \\\n    -d "recipient[email]=given.family@mollie.com" \\\n    -d "recipient[postalCode]=1000 AA" \\\n    -d "recipient[streetAndNumber]=Street 1" \\\n    -d "recipient[city]=Amsterdam" \\\n    -d "recipient[country]=nl" \\\n    -d "recipient[locale]=nl_NL" \\\n    -d "lines[0][description]=Product number 1" \\\n    -d "lines[0][quantity]=1" \\\n    -d "lines[0][vatRate]=21.00" \\\n    -d "lines[0][unitPrice][currency]=EUR" \\\n    -d "lines[0][unitPrice][value]=12.50" \\\n    -d "isEInvoice=false"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\CreateSalesInvoiceRequest;\nuse Mollie\\Api\\Http\\Data\\Money;\nuse Mollie\\Api\\Http\\Data\\Recipient;\nuse Mollie\\Api\\Http\\Data\\InvoiceLine;\nuse Mollie\\Api\\Http\\Data\\DataCollection;\nuse Mollie\\Api\\Types\\RecipientType;\nuse Mollie\\Api\\Types\\VatScheme;\nuse Mollie\\Api\\Types\\VatMode;\nuse Mollie\\Api\\Types\\PaymentTerm;\nuse Mollie\\Api\\Types\\SalesInvoiceStatus;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$recipient = new Recipient(\n    type: RecipientType::CONSUMER,\n    email: 'given.family@mollie.com',\n    streetAndNumber: 'Street 1',\n    postalCode: '1000 AA',\n    city: 'Amsterdam',\n    country: 'NL',\n    locale: 'nl_NL',\n    givenName: 'Given',\n    familyName: 'Family'\n);\n\n$invoiceLines = new DataCollection([\n    new InvoiceLine(\n        description: 'Product number 1',\n        quantity: 1,\n        vatRate: '21.00',\n        unitPrice: new Money(currency: 'EUR', value: '12.50')\n    )\n]);\n\n$request = new CreateSalesInvoiceRequest(\n    currency: 'EUR',\n    status: SalesInvoiceStatus::DRAFT,\n    vatScheme: VatScheme::STANDARD,\n    vatMode: VatMode::INCLUSIVE,\n    paymentTerm: PaymentTerm::DAYS_30,\n    recipientIdentifier: 'customer-12354123',\n    recipient: $recipient,\n    lines: $invoiceLines,\n    profileId: 'pfl_QkEhN94Ba',\n    isEInvoice: false\n);\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "201", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    def list(
        self,
        *,
        from_: OptionalNullable[str] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        testmode: Optional[bool] = None,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        url_override: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.ListSalesInvoicesResponse]:
        r"""List sales invoices

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a list of all sales invoices created through the API.

        The results are paginated.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param from_: Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
            result set.
        :param limit: The maximum number of items to return. Defaults to 50 items.
        :param testmode: Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
            parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
            setting the `testmode` query parameter to `true`.

            Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListSalesInvoicesRequest(
            from_=from_,
            limit=limit,
            testmode=testmode,
            idempotency_key=idempotency_key,
        )

        req = self._build_request(
            method="GET",
            path="/v2/sales-invoices",
            base_url=base_url,
            url_variables=url_variables,
            url_override=url_override,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            _globals=models.ListSalesInvoicesGlobals(
                testmode=self.sdk_configuration.globals.testmode,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list-sales-invoices",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X GET https://api.mollie.com/v2/sales-invoices \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\GetPaginatedSalesInvoicesRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new GetPaginatedSalesInvoicesRequest();\n\n$salesInvoices = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> Optional[models.ListSalesInvoicesResponse]:
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            next_url_match = JSONPath("$._links.next.href").parse(body)
            if len(next_url_match) == 0:
                return None

            next_url = next_url_match[0]
            if not next_url:
                return None

            if next_url[0] == "/":
                url = self._get_url(base_url, url_variables)
                next_url = url + next_url

            return self.list(
                from_=from_,
                limit=limit,
                testmode=testmode,
                idempotency_key=idempotency_key,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
                url_override=next_url,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return models.ListSalesInvoicesResponse(
                result=unmarshal_json_response(
                    models.ListSalesInvoicesResponseBody, http_res
                ),
                next=next_func,
            )
        if utils.match_response(http_res, ["400", "429"], "application/hal+json"):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        from_: OptionalNullable[str] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        testmode: Optional[bool] = None,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        url_override: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.ListSalesInvoicesResponse]:
        r"""List sales invoices

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a list of all sales invoices created through the API.

        The results are paginated.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param from_: Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
            result set.
        :param limit: The maximum number of items to return. Defaults to 50 items.
        :param testmode: Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
            parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
            setting the `testmode` query parameter to `true`.

            Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListSalesInvoicesRequest(
            from_=from_,
            limit=limit,
            testmode=testmode,
            idempotency_key=idempotency_key,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/sales-invoices",
            base_url=base_url,
            url_variables=url_variables,
            url_override=url_override,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            _globals=models.ListSalesInvoicesGlobals(
                testmode=self.sdk_configuration.globals.testmode,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list-sales-invoices",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X GET https://api.mollie.com/v2/sales-invoices \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\GetPaginatedSalesInvoicesRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new GetPaginatedSalesInvoicesRequest();\n\n$salesInvoices = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> Awaitable[Optional[models.ListSalesInvoicesResponse]]:
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            async def empty_result():
                return None

            next_url_match = JSONPath("$._links.next.href").parse(body)
            if len(next_url_match) == 0:
                return empty_result()

            next_url = next_url_match[0]
            if not next_url:
                return empty_result()

            if next_url[0] == "/":
                url = self._get_url(base_url, url_variables)
                next_url = url + next_url

            return self.list_async(
                from_=from_,
                limit=limit,
                testmode=testmode,
                idempotency_key=idempotency_key,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
                url_override=next_url,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return models.ListSalesInvoicesResponse(
                result=unmarshal_json_response(
                    models.ListSalesInvoicesResponseBody, http_res
                ),
                next=next_func,
            )
        if utils.match_response(http_res, ["400", "429"], "application/hal+json"):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    def get(
        self,
        *,
        sales_invoice_id: str,
        testmode: Optional[bool] = None,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Get sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a single sales invoice by its ID.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param testmode: Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
            parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
            setting the `testmode` query parameter to `true`.

            Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            testmode=testmode,
            idempotency_key=idempotency_key,
        )

        req = self._build_request(
            method="GET",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            _globals=models.GetSalesInvoiceGlobals(
                testmode=self.sdk_configuration.globals.testmode,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X GET https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\GetSalesInvoiceRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new GetSalesInvoiceRequest('invoice_4Y0eZitmBnQ6IDoMqZQKh');\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(http_res, ["404", "429"], "application/hal+json"):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def get_async(
        self,
        *,
        sales_invoice_id: str,
        testmode: Optional[bool] = None,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Get sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a single sales invoice by its ID.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param testmode: Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
            parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
            setting the `testmode` query parameter to `true`.

            Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            testmode=testmode,
            idempotency_key=idempotency_key,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            _globals=models.GetSalesInvoiceGlobals(
                testmode=self.sdk_configuration.globals.testmode,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X GET https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\GetSalesInvoiceRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new GetSalesInvoiceRequest('invoice_4Y0eZitmBnQ6IDoMqZQKh');\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "# We don't have a Node.js code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "# We don't have a Python code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(http_res, ["404", "429"], "application/hal+json"):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    def update(
        self,
        *,
        sales_invoice_id: str,
        idempotency_key: Optional[str] = None,
        request_body: Optional[
            Union[
                models.UpdateSalesInvoiceRequestBody,
                models.UpdateSalesInvoiceRequestBodyTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Update sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Certain details of an existing sales invoice can be updated. For `draft` it is all values listed below, but for
        statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and `emailDetails`,
        respectively).

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            idempotency_key=idempotency_key,
            request_body=utils.get_pydantic_model(
                request_body, Optional[models.UpdateSalesInvoiceRequestBody]
            ),
        )

        req = self._build_request(
            method="PATCH",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[models.UpdateSalesInvoiceRequestBody],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X PATCH https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM" \\\n    -d "paymentTerm=14 days"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\UpdateSalesInvoiceRequest;\nuse Mollie\\Api\\Types\\PaymentTerm;\nuse Mollie\\Api\\Types\\SalesInvoiceStatus;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new UpdateSalesInvoiceRequest(\n    id: 'invoice_4Y0eZitmBnQ6IDoMqZQKh',\n    status: SalesInvoiceStatus::DRAFT,\n    recipientIdentifier: 'customer-12354123',\n    paymentTerm: PaymentTerm::DAYS_14,\n    isEInvoice: false\n);\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "/*\nWe don't have a Node.js code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n*/",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "'''\nWe don't have a Python code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n'''",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def update_async(
        self,
        *,
        sales_invoice_id: str,
        idempotency_key: Optional[str] = None,
        request_body: Optional[
            Union[
                models.UpdateSalesInvoiceRequestBody,
                models.UpdateSalesInvoiceRequestBodyTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SalesInvoiceResponse:
        r"""Update sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Certain details of an existing sales invoice can be updated. For `draft` it is all values listed below, but for
        statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and `emailDetails`,
        respectively).

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UpdateSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            idempotency_key=idempotency_key,
            request_body=utils.get_pydantic_model(
                request_body, Optional[models.UpdateSalesInvoiceRequestBody]
            ),
        )

        req = self._build_request_async(
            method="PATCH",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[models.UpdateSalesInvoiceRequestBody],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X PATCH https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM" \\\n    -d "paymentTerm=14 days"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\UpdateSalesInvoiceRequest;\nuse Mollie\\Api\\Types\\PaymentTerm;\nuse Mollie\\Api\\Types\\SalesInvoiceStatus;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new UpdateSalesInvoiceRequest(\n    id: 'invoice_4Y0eZitmBnQ6IDoMqZQKh',\n    status: SalesInvoiceStatus::DRAFT,\n    recipientIdentifier: 'customer-12354123',\n    paymentTerm: PaymentTerm::DAYS_14,\n    isEInvoice: false\n);\n\n$salesInvoice = $mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "/*\nWe don't have a Node.js code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n*/",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "'''\nWe don't have a Python code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n'''",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/hal+json"):
            return unmarshal_json_response(models.SalesInvoiceResponse, http_res)
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    def delete(
        self,
        *,
        sales_invoice_id: str,
        idempotency_key: Optional[str] = None,
        delete_values_sales_invoice: Optional[
            Union[
                models.DeleteValuesSalesInvoice,
                models.DeleteValuesSalesInvoiceTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
        [Update sales invoice](update-sales-invoice) endpoint instead.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param delete_values_sales_invoice:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            idempotency_key=idempotency_key,
            delete_values_sales_invoice=utils.get_pydantic_model(
                delete_values_sales_invoice, Optional[models.DeleteValuesSalesInvoice]
            ),
        )

        req = self._build_request(
            method="DELETE",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.delete_values_sales_invoice if request is not None else None,
                False,
                True,
                "json",
                Optional[models.DeleteValuesSalesInvoice],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X DELETE https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\DeleteSalesInvoiceRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new DeleteSalesInvoiceRequest('invoice_4Y0eZitmBnQ6IDoMqZQKh');\n\n$mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "/*\nWe don't have a Node.js code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n*/",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "'''\nWe don't have a Python code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n'''",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def delete_async(
        self,
        *,
        sales_invoice_id: str,
        idempotency_key: Optional[str] = None,
        delete_values_sales_invoice: Optional[
            Union[
                models.DeleteValuesSalesInvoice,
                models.DeleteValuesSalesInvoiceTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete sales invoice

        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
        [Update sales invoice](update-sales-invoice) endpoint instead.

        If set, this operation will use one of `api_key`, `advanced_access_token`, or `o_auth` from the global security.

        :param sales_invoice_id: Provide the ID of the related sales invoice.
        :param idempotency_key: A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        :param delete_values_sales_invoice:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSalesInvoiceRequest(
            sales_invoice_id=sales_invoice_id,
            idempotency_key=idempotency_key,
            delete_values_sales_invoice=utils.get_pydantic_model(
                delete_values_sales_invoice, Optional[models.DeleteValuesSalesInvoice]
            ),
        )

        req = self._build_request_async(
            method="DELETE",
            path="/v2/sales-invoices/{salesInvoiceId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/hal+json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.delete_values_sales_invoice if request is not None else None,
                False,
                True,
                "json",
                Optional[models.DeleteValuesSalesInvoice],
            ),
            allow_empty_value=None,
            allowed_fields=["api_key", "advanced_access_token", "o_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 5000, 2, 7500), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5xx"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete-sales-invoice",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["Sales Invoices API"],
                extensions={
                    "x-readme": {
                        "code-samples": [
                            {
                                "code": 'curl -X DELETE https://api.mollie.com/v2/sales-invoices/invoice_4Y0eZitmBnQ6IDoMqZQKh \\\n    -H "Authorization: Bearer live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"',
                                "language": "shell",
                            },
                            {
                                "code": "<?php\nuse Mollie\\Api\\MollieApiClient;\nuse Mollie\\Api\\Http\\Requests\\DeleteSalesInvoiceRequest;\n\n$mollie = new MollieApiClient();\n$mollie->setApiKey('live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');\n\n$request = new DeleteSalesInvoiceRequest('invoice_4Y0eZitmBnQ6IDoMqZQKh');\n\n$mollie->send($request);",
                                "install": "composer require mollie/mollie-api-php",
                                "language": "php",
                            },
                            {
                                "code": "/*\nWe don't have a Node.js code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n*/",
                                "install": "npm install @mollie/api-client",
                                "language": "node",
                            },
                            {
                                "code": "'''\nWe don't have a Python code example for this\nAPI call yet.\n\nIf you have some time to spare, feel free to\nshare suggestions on our Discord:\nhttps://discord.gg/VaTVkXB4aQ\n'''",
                                "install": "pip install mollie-api-python",
                                "language": "python",
                            },
                            {
                                "code": "# We don't have a Ruby code example for this\n# API call yet.\n#\n# If you have some time to spare, feel free to\n# share suggestions on our Discord:\n# https://discord.gg/VaTVkXB4aQ",
                                "install": "gem install mollie-api-ruby",
                                "language": "ruby",
                            },
                        ]
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return
        if utils.match_response(
            http_res, ["404", "422", "429"], "application/hal+json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)
